import React from 'react';
import { TransactionData, FraudInsight } from '@/pages/Index';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { FileText, Download, FileSpreadsheet } from 'lucide-react';
import * as jsPDF from 'jspdf';

interface ExportReportsProps {
  data: TransactionData[];
  insights: FraudInsight[];
}

export const ExportReports: React.FC<ExportReportsProps> = ({ data, insights }) => {
  const exportToCsv = () => {
    const headers = ['TransactionID', 'StoreID', 'ProductID', 'PaymentType', 'Amount', 'Timestamp', 'RiskLevel', 'FraudScore', 'FraudType'];
    const csvContent = [
      headers.join(','),
      ...data.map(row => [
        row.TransactionID,
        row.StoreID,
        row.ProductID,
        row.PaymentType,
        row.Amount,
        row.Timestamp,
        row.riskLevel || 'Low',
        row.fraudScore || 0,
        row.fraudType || 'None'
      ].join(','))
    ].join('\n');

    const blob = new Blob([csvContent], { type: 'text/csv' });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `fraud_analysis_${new Date().toISOString().split('T')[0]}.csv`;
    a.click();
    window.URL.revokeObjectURL(url);
  };

  const exportToPdf = () => {
    const doc = new (jsPDF as any)();
    
    // Header
    doc.setFontSize(20);
    doc.setTextColor(234, 88, 12); // Orange color
    doc.text('Retail Risk Radar', 20, 30);
    doc.setFontSize(16);
    doc.setTextColor(0, 0, 0);
    doc.text('Fraud Detection Report', 20, 45);
    
    // Date
    doc.setFontSize(10);
    doc.setTextColor(100, 100, 100);
    doc.text(`Generated: ${new Date().toLocaleDateString()}`, 20, 55);
    
    // Summary
    doc.setFontSize(14);
    doc.setTextColor(0, 0, 0);
    doc.text('Executive Summary', 20, 75);
    
    const totalTransactions = data.length;
    const highRisk = data.filter(t => t.riskLevel === 'High').length;
    const fraudRate = ((highRisk / totalTransactions) * 100).toFixed(1);
    
    doc.setFontSize(11);
    doc.text(`Total Transactions Analyzed: ${totalTransactions.toLocaleString()}`, 20, 90);
    doc.text(`High Risk Transactions: ${highRisk}`, 20, 100);
    doc.text(`Overall Fraud Rate: ${fraudRate}%`, 20, 110);
    
    // Key Insights
    doc.setFontSize(14);
    doc.text('Key AI Insights', 20, 130);
    
    let yPosition = 145;
    insights.slice(0, 5).forEach((insight, index) => {
      doc.setFontSize(11);
      doc.setTextColor(234, 88, 12);
      doc.text(`${index + 1}. ${insight.type}`, 20, yPosition);
      yPosition += 10;
      
      doc.setFontSize(10);
      doc.setTextColor(0, 0, 0);
      const description = doc.splitTextToSize(insight.description, 170);
      doc.text(description, 25, yPosition);
      yPosition += description.length * 5 + 5;
    });
    
    // Footer
    doc.setFontSize(8);
    doc.setTextColor(100, 100, 100);
    doc.text('This report was generated by Retail Risk Radar AI-powered fraud detection system.', 20, 280);
    
    doc.save(`fraud_report_${new Date().toISOString().split('T')[0]}.pdf`);
  };

  const fraudStats = {
    totalTransactions: data.length,
    highRisk: data.filter(t => t.riskLevel === 'High').length,
    mediumRisk: data.filter(t => t.riskLevel === 'Medium').length,
    lowRisk: data.filter(t => t.riskLevel === 'Low').length,
    totalFraudAmount: data.filter(t => t.riskLevel === 'High').reduce((sum, t) => sum + t.Amount, 0)
  };

  return (
    <div className="space-y-6">
      <Card className="bg-slate-800 border-slate-700">
        <CardHeader>
          <CardTitle className="text-white flex items-center space-x-2">
            <FileText className="h-5 w-5" />
            <span>Export Reports</span>
          </CardTitle>
          <p className="text-slate-400">
            Generate comprehensive fraud analysis reports for audit and compliance
          </p>
        </CardHeader>
        <CardContent className="space-y-6">
          {/* Report Summary */}
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
            <div className="p-4 bg-slate-700 rounded-lg">
              <h3 className="text-white font-semibold">Total Transactions</h3>
              <p className="text-2xl font-bold text-blue-400">{fraudStats.totalTransactions.toLocaleString()}</p>
            </div>
            <div className="p-4 bg-slate-700 rounded-lg">
              <h3 className="text-white font-semibold">High Risk</h3>
              <p className="text-2xl font-bold text-red-400">{fraudStats.highRisk}</p>
            </div>
            <div className="p-4 bg-slate-700 rounded-lg">
              <h3 className="text-white font-semibold">Fraud Rate</h3>
              <p className="text-2xl font-bold text-orange-400">
                {((fraudStats.highRisk / fraudStats.totalTransactions) * 100).toFixed(1)}%
              </p>
            </div>
            <div className="p-4 bg-slate-700 rounded-lg">
              <h3 className="text-white font-semibold">Potential Loss</h3>
              <p className="text-2xl font-bold text-green-400">${fraudStats.totalFraudAmount.toLocaleString()}</p>
            </div>
          </div>

          {/* Export Options */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <Card className="bg-slate-700 border-slate-600">
              <CardHeader>
                <CardTitle className="text-white flex items-center space-x-2">
                  <FileSpreadsheet className="h-5 w-5" />
                  <span>CSV Export</span>
                </CardTitle>
                <p className="text-slate-400 text-sm">
                  Raw transaction data with fraud scores and risk levels
                </p>
              </CardHeader>
              <CardContent>
                <Button
                  onClick={exportToCsv}
                  className="w-full bg-green-600 hover:bg-green-700 text-white"
                >
                  <Download className="h-4 w-4 mr-2" />
                  Download CSV Report
                </Button>
                <p className="text-xs text-slate-500 mt-2">
                  Includes all transaction data, fraud scores, and AI analysis results
                </p>
              </CardContent>
            </Card>

            <Card className="bg-slate-700 border-slate-600">
              <CardHeader>
                <CardTitle className="text-white flex items-center space-x-2">
                  <FileText className="h-5 w-5" />
                  <span>PDF Report</span>
                </CardTitle>
                <p className="text-slate-400 text-sm">
                  Executive summary with key insights and recommendations
                </p>
              </CardHeader>
              <CardContent>
                <Button
                  onClick={exportToPdf}
                  className="w-full bg-gradient-to-r from-orange-500 to-red-500 hover:from-orange-600 hover:to-red-600 text-white"
                >
                  <Download className="h-4 w-4 mr-2" />
                  Generate PDF Report
                </Button>
                <p className="text-xs text-slate-500 mt-2">
                  Professional report with charts, insights, and compliance data
                </p>
              </CardContent>
            </Card>
          </div>

          {/* Report Content Preview */}
          <Card className="bg-slate-700 border-slate-600">
            <CardHeader>
              <CardTitle className="text-white">Report Content Preview</CardTitle>
            </CardHeader>
            <CardContent>
              <div className="space-y-4 text-sm">
                <div>
                  <h4 className="text-white font-semibold">Executive Summary</h4>
                  <p className="text-slate-400">Overview of fraud detection results and key metrics</p>
                </div>
                <div>
                  <h4 className="text-white font-semibold">AI Insights</h4>
                  <p className="text-slate-400">Machine learning findings and pattern analysis</p>
                </div>
                <div>
                  <h4 className="text-white font-semibold">Geographic Analysis</h4>
                  <p className="text-slate-400">Store-by-store breakdown and hotspot identification</p>
                </div>
                <div>
                  <h4 className="text-white font-semibold">Recommendations</h4>
                  <p className="text-slate-400">Actionable steps to reduce fraud risk</p>
                </div>
                <div>
                  <h4 className="text-white font-semibold">Compliance Data</h4>
                  <p className="text-slate-400">Audit trail and regulatory compliance information</p>
                </div>
              </div>
            </CardContent>
          </Card>
        </CardContent>
      </Card>
    </div>
  );
};
